version: '3'

volumes:
  database:
  redis:

services:
  traefik:
    container_name: traefik
    image: traefik:1.5-alpine
    dns: ${DNS}
    restart: always
    ports:
      - 8080:8080
      - 80:80
    command: --api --docker --loglevel=debug \
             --entryPoints="Name:http Address::80" --docker.endpoint="unix:///var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:lb.riskiwah.net"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http"
      - "com.centurylinklabs.watchtower.enable: true"

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    restart: always
    command: --schedule "0 0 5 * * 1" --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ghost:
    container_name: ghost-blog
    image: ghost
    restart: always
    ports:
      - 2368:2368
    labels:
      - "traefik.backend=ghost"
      - "traefik.frontend.rule=Host:blog.riskiwah.net"
      - "traefik.port=2368"
      - "traefik.frontend.entryPoints=http"
      - "com.centurylinklabs.watchtower.enable: true"

  jenkins:
    container_name: jenkins
    image: jenkins
    restart: always
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    labels:
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:jenkins.riskiwah.net"
      - "traefik.port=8080"
      # - "traefik.port=50000"
      - "traefik.frontend.entryPoints=http"
      - "com.centurylinklabs.watchtower.enable: true"

  #### nextcloud ####
  nextcloud-database:
    container_name: nextcloud-database
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NC_DB_PASSWORD}
      MYSQL_PASSWORD: ${NC_DB_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    labels:
      - "com.centurylinklabs.watchtower.enable: true"

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    labels:
      - "com.centurylinklabs.watchtower.enable: true"

  nextcloud:
    container_name: nextcloud
    image: wonderfall/nextcloud
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - nextcloud-database
      - nextcloud-redis
    links:
      - nextcloud-database:nextcloud-database
      - nextcloud-redis:nextcloud-redis
    volumes:
      - ./volume/cloud/data:/data
      - ./volume/cloud/config:/config
      - ./volume/cloud/apps:/apps2
      - ./volume/cloud/themes:/nextcloud/themes
    environment:
      UID: 1000
      GID: 1000
      UPLOAD_MAX_SIZE: 100G
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      CRON_PERIOD: 15m
      TZ: Asia/Jakarta
      DB_TYPE: mysql
      DB_NAME: nextcloud
      DB_USER: nextcloud
      DB_PASSWORD: ${NC_DB_PASSWORD}
      DB_HOST: nextcloud-database
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:nc.riskiwah.net"
      - "traefik.port=8888"
      - "traefik.frontend.entryPoints=http"
      - "com.centurylinklabs.watchtower.enable: true"
