version: '3'

services:
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    restart: always
    ports:
      - "8888:8888"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
